# Generated by Django 4.1.2 on 2022-10-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Listing',
        ),
    ]
