# Generated by Django 4.1.2 on 2022-10-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
